# Generated by Django 2.2 on 2021-05-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officalZooApp', '0002_auto_20210513_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='shopZoo',
        ),
        migrations.AddField(
            model_name='shop',
            name='zoos',
            field=models.ManyToManyField(related_name='shops', to='officalZooApp.Zoo'),
        ),
    ]
